# Generated by Django 5.2.3 on 2025-07-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmu_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=1)),
                ('intake', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=30)),
            ],
        ),
    ]
