# Generated by Django 4.2.8 on 2025-07-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lmu_id',
            field=models.IntegerField(unique=True),
        ),
    ]
