# Generated by Django 4.2.8 on 2025-07-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_lmu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='lmu_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
